parameters:
  _param:
    prometheus_server_config_directory: /srv/prometheus
    prometheus_server_data_directory: /data
  prometheus:
    server:
      dir:
        config_in_container: ${_param:prometheus_server_config_directory}
