parameters:
  jenkins:
    client:
      job:
        docker-build-images-security-monkey-docker:
          name: docker-build-images-security-monkey-docker
          discard:
            build:
              keep_num: 25
            artifact:
              keep_num: 25
          type: workflow-scm
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/oss/jenkins/pipelines"
            credentials: "gerrit"
            script: docker-build-image-security-monkey-pipeline.groovy
          trigger:
            gerrit:
              project:
                "oss/docker-security-monkey":
                  branches:
                    - master
              skip_vote:
                - successful
                - failed
                - unstable
                - not_built
              event:
                patchset:
                  - created:
                      excludeDrafts: false
                      excludeNoCodeChange: false
                change:
                  - merged
                comment:
                  - addedContains:
                      commentAddedCommentContains: 'rebuild'
          param:
            IMAGE_NAME:
              type: string
              default: "security-monkey"
            IMAGE_TAGS:
              type: string
              default: ""
            CREDENTIALS_ID:
              type: string
              default: "gerrit"
            DOCKER_REGISTRY:
              type: string
              default: "docker-dev-virtual.docker.mirantis.net"
            PROJECT_NAMESPACE:
              type: string
              default: "oss"
            DOCKERFILE_PATH:
              type: string
              default: "security-monkey/Dockerfile"
            CONTEXT_PATH:
              type: string
              default: "."