parameters:
  linux:
    network:
      host:
        localhost_hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:fqdn}
          - ${linux:network:hostname}
