#
# Jobs to update packages on given Salt master environment
#
parameters:
  _param:
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
  jenkins:
    client:
      job:
        deploy-upgrade-opencontrail:
          type: workflow-scm
          concurrent: true
          display_name: "Deploy - upgrade Opencontrail"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            credentials: "gerrit"
            script: opencontrail-upgrade.groovy
          param:
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            STAGE_CONTROLLERS_UPGRADE:
              type: boolean
              default: 'true'
              description: "Run upgrade on Opencontrail controllers"
            STAGE_ANALYTICS_UPGRADE:
              type: boolean
              default: 'true'
              description: "Run upgrade on Opencontrail analytics"
            STAGE_COMPUTES_UPGRADE:
              type: boolean
              default: 'true'
              description: "Run upgrade on Opencontrail compute nodes"
            COMPUTE_TARGET_SERVERS:
              type: string
              default: "cmp*"
              description: Salt compound target to match nodes to be updated [*, G@osfamily:debian].
            COMPUTE_TARGET_SUBSET_LIVE:
              type: string
              default: '1'
              description: Number of selected nodes to live apply compute upgrade.
            STAGE_CONTROLLERS_ROLLBACK:
              type: boolean
              default: 'false'
              description: "Run rollback on Opencontrail controllers"
            STAGE_ANALYTICS_ROLLBACK:
              type: boolean
              default: 'false'
              description: "Run rollback on Opencontrail analytics"
            STAGE_COMPUTES_ROLLBACK:
              type: boolean
              default: 'false'
              description: "Run rollback on Opencontrail compute nodes"
