parameters:
  haproxy:
    proxy:
      listen:
        k8s_secure:
          type: kubernetes
          options:
            - ssl-hello-chk
          binds:
          - address: ${_param:cluster_vip_address}
            port: 443
          servers:
          - name: ${_param:cluster_node01_hostname}
            host: ${_param:cluster_node01_address}
            port: 6443
            params: check
          - name: ${_param:cluster_node02_hostname}
            host: ${_param:cluster_node02_address}
            port: 6443
            params: check
          - name: ${_param:cluster_node03_hostname}
            host: ${_param:cluster_node03_address}
            port: 6443
            params: check
          timeout:
            server: 10m
            client: 10m
