classes:
- service.grafana.server.single
parameters:
  _param:
    grafana_port: 3000
    grafana_user: admin
    grafana_password: admin
  grafana:
    server:
      enabled: true
      bind:
        address: ${_param:single_address}
        port: ${_param:grafana_port}
      database:
        engine: mysql
        host: ${_param:openstack_database_address}
        port: 3306
        name: grafana
        user: grafana
        password: ${_param:mysql_grafana_password}
      auth:
        basic:
          enabled: true
      admin:
        user: ${_param:grafana_user}
        password: ${_param:grafana_password}
      dashboards:
        enabled: false
        path: /var/lib/grafana/dashboards
