parameters:
  _param:
    analytics_tweeviz_release: ${_param:analytics_release_prefix}tweeviz
  helm:
    client:
      releases:
        analytics-pipeline-tweeviz:
          enabled: ${_param:analytics_enabled}
          name: ${_param:analytics_tweeviz_release}
          chart: ${_param:analytics_repo}/tweeviz
          values:
            minPopularity: 1
            topListSize: 25
            storage: hdfs
            hdfs:
              deployChart: false
              externalAddress: ${_param:analytics_hdfs_address}
              path: /
              externalPort: 8020
