classes:
- system.grafana.client
- system.grafana.client.datasource.influxdb
parameters:
  _param:
    grafana_address: ${_param:stacklight_monitor_address}
    grafana_influxdb_address: ${_param:grafana_influxdb_host}
    grafana_influxdb_port: ${_param:influxdb_port}
    grafana_influxdb_user: lma
    grafana_influxdb_password: ${_param:influxdb_stacklight_password}
    grafana_influxdb_database: lma
    grafana_influxdb_ds_name: lma
