parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'pushgateway'
              domain:
              - 'tasks.monitoring_pushgateway'
              type: A
              port: ${prometheus:pushgateway:bind:port}
            - name: 'prometheus'
              domain:
              - 'tasks.monitoring_server'
              type: A
              port: ${prometheus:server:bind:port}
            - name: 'alertmanager'
              domain:
              - 'tasks.monitoring_alertmanager'
              type: A
              port: ${prometheus:alertmanager:bind:port}
            - name: 'remote_agent'
              domain:
              - 'tasks.monitoring_remote_agent'
              type: A
              port: ${telegraf:remote_agent:output:prometheus_client:bind:port}
            - name: 'remote_storage_adapter'
              domain:
              - 'tasks.monitoring_remote_storage_adapter'
              type: A
              port: ${prometheus:remote_storage_adapter:bind:port}
