parameters:
  _param:
    docker_image_jenkins: tcpcloud/jenkins:2.73
    jenkins_master_extra_opts: ""
    jenkins_master_executors_num: 4
  docker:
    client:
      stack:
        jenkins:
          service:
            master:
              environment:
                JAVA_OPTS: " -server -XX:+AlwaysPreTouch -Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1 -Djenkins.install.runSetupWizard=false -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Dhudson.footerURL=https://www.mirantis.com ${_param:jenkins_master_extra_opts}"
                JENKINS_NUM_EXECUTORS: ${_param:jenkins_master_executors_num}
              deploy:
                restart_policy:
                  condition: any
              image: ${_param:docker_image_jenkins}
              ports:
                - 18081:8080
                - 50001:50000
              volumes:
                - /srv/volumes/jenkins:/var/jenkins_home
                - /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts:ro
