parameters:
  _param:
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
    jenkins_salt_model_name: "salt"
  jenkins:
    client:
      job:
        docker-cleanup-pipeline:
          name: docker-cleanup
          discard:
            build:
              keep_num: 3
            artifact:
              keep_num: 3
          type: workflow-scm
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            credentials: "gerrit"
            script: docker-cleanup-pipeline.groovy
          trigger:
            timer:
              spec: "H H * * *"
          param:
              SALT_MASTER_URL:
                type: string
                default: "${_param:jenkins_salt_api_url}"
              SALT_MASTER_CREDENTIALS:
                type: string
                default: "salt"
              TEST_DATE_STRING:
                type: string
                default: "yesterday"
                description: "Date string for comparison determining deletion of docker container"
