parameters:
  jenkins:
    client:
      view:
        Docker:
          enabled: true
          type: ListView
          include_regex: ".*docker.*"
      job_template:
        docker-build-image:
          name: docker-build-image-{{name}}-{{branch}}
          jobs:
            - name: gerrit
              branch: "2.12.7"
              tags: "2.12.7"
              dockerfile: "Dockerfile"
            - name: gerrit
              branch: "2.13.6"
              tags: "2.13.6 latest"
              dockerfile: "Dockerfile"
            - name: jenkins
              branch: "2.32.3"
              tags: "2.32"
              dockerfile: "Dockerfile"
            - name: jenkins
              branch: "2.73"
              tags: "2.73 latest"
              dockerfile: "Dockerfile"
            - name: phpldapadmin
              branch: "master"
              tags: "latest"
              dockerfile: "image/Dockerfile"
            - name: openldap
              branch: "master"
              tags: "latest"
              dockerfile: "image/Dockerfile"
            - name: mysql
              branch: "master"
              tags: "5.6 latest"
              dockerfile: "5.6/Dockerfile"
          template:
            discard:
              build:
                keep_num: 5
              artifact:
                keep_num: 5
            type: workflow-scm
            concurrent: true
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
              credentials: "gerrit"
              script: docker-build-image-pipeline.groovy
            trigger:
              gerrit:
                project:
                  "mk/docker-{{name}}":
                    branches:
                      - "{{branch}}"
                event:
                  ref:
                    - updated: {}
            param:
              IMAGE_NAME:
                type: string
                default: "tcpcloud/{{name}}"
              IMAGE_GIT_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/docker-{{name}}"
              IMAGE_BRANCH:
                type: string
                default: "{{branch}}"
              IMAGE_CREDENTIALS_ID:
                type: string
                default: "gerrit"
              IMAGE_TAGS:
                type: string
                default: "{{tags}}"
              DOCKERFILE_PATH:
                type: string
                default: "{{dockerfile}}"
              REGISTRY_URL:
                type: string
                default: ""
              REGISTRY_CREDENTIALS_ID:
                type: string
                default: "dockerhub"
              DOCKER_GIT_TAG:
                type: boolean
                default: "true"
