parameters:
  swift:
    ring_builder:
      enabled: true
      rings:
        - partition_power: 9
          replicas: 3
          hours: 1
          region: 1
          devices:
            - address: ${_param:swift_storage_node01_address}
              device: ${_param:swift_device0}
            - address: ${_param:swift_storage_node02_address}
              device: ${_param:swift_device0}
            - address: ${_param:swift_storage_node03_address}
              device: ${_param:swift_device0}