classes:
  - system.jenkins.client.job.deploy.lab.deploy
parameters:
  _param:
    jenkins_deploy_jobs:
      # mk20
      - stack_name: virtual_mk20_advanced
        stack_env: devcloud
        stack_install: core,openstack
        stack_type: heat
        stack_test: ""
        job_timer: ""
      - stack_name: virtual_mk20_basic
        stack_env: devcloud
        stack_install: core,openstack
        stack_type: heat
        stack_test: ""
        job_timer: ""
      # mk22
      - stack_name: virtual_mk22_advanced
        stack_env: devcloud
        stack_install: core,openstack
        stack_type: heat
        stack_test: ""
        job_timer: ""
      - stack_name: virtual_mk22_basic
        stack_env: devcloud
        stack_install: core,openstack
        stack_type: heat
        stack_test: ""
        job_timer: ""
