#
# Jobs to update packages on given Salt master environment
#
parameters:
  _param:
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
  jenkins:
    client:
      job:
        deploy-zookeeper-restore:
          type: workflow-scm
          concurrent: true
          display_name: "Zookeeper - restore"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            credentials: "gerrit"
            script: restore-zookeeper.groovy
          param:
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
