classes:
- service.kubernetes.master.cluster
- service.keepalived.cluster.single
- service.haproxy.proxy.single
- system.haproxy.proxy.listen.kubernetes.apiserver
parameters:
  _param:
    kubernetes_netchecker_agent_image: quay.io/l23network/k8s-netchecker-agent:v1.0
    kubernetes_netchecker_server_image: quay.io/l23network/k8s-netchecker-server:v1.0
  kubernetes:
    master:
      container: false
      network:
        engine: calico
        private_ip_range: ${_param:calico_private_network}/${_param:calico_private_netmask}
        prometheus:
          enabled: true
